spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/website
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:com.ilyaskrypnik.website.db.changelog\db.changelog-master.yaml



application:
  external-service:
    email-service:
      name: mail-service
      main-uri: http://localhost:8081
      send-registration-success-email: /v1/sendRegistrationSuccess

