spring:
  datasource:
    url: jdbc:postgresql://localhost/website
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
